services:
  sketchtogether.api:
    image: ${DOCKER_REGISTRY-}sketchtogetherapi
    build:
      context: .
      dockerfile: SketchTogether.API/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - sketchtogether.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=sketchtogether.database;Port=5432;Database=sketchtogether;User Id=postgres;Password=YourStrong!Passw0rd;"
      - "JWT__SecretKey=VaccinaCare_SECRETKEY_SIEUCAPBAOMAT_VAYMACHUADU16KYTU"
  sketchtogether.database:
    image: postgres:15
    container_name: sketchtogether.database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=YourStrong!Passw0rd
      - POSTGRES_DB=sketchtogether
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: